# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME=powerlevel10k/powerlevel10k

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Tmux Settings
ZSH_TMUX_AUTOSTART=true

# Key Bindings
bindkey '^ ' autosuggest-accept

# Plugins
plugins=(git pip ssh-agent sudo tmux chucknorris common-aliases zsh-autosuggestions zsh-syntax-highlighting docker docker-compose)

if [[ "$OSTYPE" =~ "darwin" ]]; then
        plugins+=(brew osx)
else
        plugins+=(debian systemd)
fi

source $ZSH/oh-my-zsh.sh

# User configuration

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='nvim'
else
  export EDITOR='nvim'
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh

# Variables settings
export PATH="/home/patcody/util/diff-so-fancy:$PATH"
export VIMRC="$HOME/.config/nvim/init.vim"

# Aliases
alias ls='lsd'
alias l='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias lt='ls --tree'

if type "nvim" > /dev/null; then	
	alias vim='nvim'
fi
